apiVersion: apps/v1
kind: Deployment
metadata:
  name: featurehub
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: featurehub
  template:
    metadata:
      labels:
        app: featurehub
    spec:
      containers:
        - image: featurehub/party-server:latest
          name: party-server
          ports:
            - containerPort: 8085
          env:
            - name: db.url
              value: postgres://db:5432/db0
            - name: db.username
              value: postgres
            - name: db.password
              value: changeme
            - name: jersey.cors.headers
              value: X-Requested-With,Authorization,Content-type,Accept-Version,Content-MD5,CSRF-Token,x-ijt,cache-control,x-featurehub,Baggagei
          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"