apiVersion: apps/v1
kind: Deployment
metadata:
  name: featurehub
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: featurehub
  template:
    metadata:
      labels:
        app: featurehub
    spec:
      containers:
        - image: featurehub/party-server:latest
          name: party-server
          ports:
            - containerPort: 8085
          command:
            - touch /etc/app-config/application.properties
            - echo "db.url=jdbc:postgres://db:5432/db0"  > /etc/app-config/application.properties
            - echo "db.username=postgres"  > /etc/app-config/application.properties
            - echo "db.password=changeme"  > /etc/app-config/application.properties
            - echo "jersey.cors.headers=X-Requested-With,Authorization,Content-type,Accept-Version,Content-MD5,CSRF-Token,x-ijt,cache-control,x-featurehub,Baggage"  > /etc/app-config/application.properties
          resources:
            limits:
              memory: "512Mi"
              cpu: "300m"